//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomCurves {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CustomCurves.LanguageResource", typeof(LanguageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Specify the axis of the parabola:.
        /// </summary>
        internal static string Axis {
            get {
                return ResourceManager.GetString("Axis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Specify the end point:.
        /// </summary>
        internal static string BasketHandleEndPoint {
            get {
                return ResourceManager.GetString("BasketHandleEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Specify the height:.
        /// </summary>
        internal static string BasketHandleHeight {
            get {
                return ResourceManager.GetString("BasketHandleHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Centers.
        /// </summary>
        internal static string BasketHandleKeyword {
            get {
                return ResourceManager.GetString("BasketHandleKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Specify the start point:.
        /// </summary>
        internal static string BasketHandleStartPoint {
            get {
                return ResourceManager.GetString("BasketHandleStartPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Specify the branch end:.
        /// </summary>
        internal static string BranchEnd {
            get {
                return ResourceManager.GetString("BranchEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current number of centers:.
        /// </summary>
        internal static string CurrentNumCenters {
            get {
                return ResourceManager.GetString("CurrentNumCenters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current number of fit points:.
        /// </summary>
        internal static string CurrentNumFitPoints {
            get {
                return ResourceManager.GetString("CurrentNumFitPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Specify the end point:.
        /// </summary>
        internal static string EndPoint {
            get {
                return ResourceManager.GetString("EndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Specify the horizontal tension:.
        /// </summary>
        internal static string HorizontalTension {
            get {
                return ResourceManager.GetString("HorizontalTension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à loaded.
        /// </summary>
        internal static string Loaded {
            get {
                return ResourceManager.GetString("Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose the number of centers [3/7]:.
        /// </summary>
        internal static string NumCenters {
            get {
                return ResourceManager.GetString("NumCenters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the number of fit points:.
        /// </summary>
        internal static string NumFitPoints {
            get {
                return ResourceManager.GetString("NumFitPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à End point X coordinate must be different from start point one..
        /// </summary>
        internal static string PointError {
            get {
                return ResourceManager.GetString("PointError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Specify the start point or [Points]:.
        /// </summary>
        internal static string StartPoint {
            get {
                return ResourceManager.GetString("StartPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Specify the summit of the parabola:.
        /// </summary>
        internal static string Summit {
            get {
                return ResourceManager.GetString("Summit", resourceCulture);
            }
        }
    }
}
